services:
  account:
    image: "vikum92/account:s6"
    container_name: account
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - microservice

  card:
    image: "vikum92/card:s6"
    container_name: card
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - microservice

  loan:
    image: "vikum92/loan:s6"
    container_name: loan
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          memory: 700M
    networks:
      - microservice

networks:
  microservice:
    driver: bridge