server:
  port: 8080
spring:
  application:
    name: account
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/account?createDatabaseIfNotExist=true
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true